### ISSUE TITLE
Create `CLinkAddress` concept

### ISSUE THREAD

**Issue by FreePhoenix888** [linksplatform/Interfaces#101]
`CLinkAddress` must check that argument is integral and unsigned

**Comment by FreePhoenix888** [comment]
@uselessgoddess , what about `std::three_way_comparable`? I think it must be constrained with `std::three_way_comparable` too

**Comment by uselessgoddess** [comment]
No.  They require operator+, operator, operator*, ....

**Comment by uselessgoddess** [comment]
Use like this style:
```c++
template <typename Self>
concept LinkType = std::is_unsigned_v<Self>;
```

**Comment by uselessgoddess** [comment]
And move to `Numbers`

**Comment by FreePhoenix888** [comment]
Closed in https://github.com/linksplatform/Interfaces/issues/113
