### ISSUE TITLE
Should we add header that undefines macros?

### ISSUE THREAD

**Issue by Konard** [linksplatform/Interfaces#87]
https://github.com/linksplatform/Interfaces/blob/master/cpp/Platform.Interfaces/Macros.h

For example, we can name this header as `Undefine_Macros.h` or `UnMacros.h`

We could add undefine macros header file to the end of `Platform.Interfaces.h` do to something like this: https://github.com/linksplatform/Ranges/blob/master/cpp/Platform.Ranges/Range.h

**Comment by uselessgoddess** [comment]
So no.
